# Spring Boot configuration
---
spring:
#  # Database
#  datasource:
#    url: "jdbc:postgresql://localhost:5432/jenkins"
#    username: postgres
#    password: pwd
#  # JPA properties
#  jpa:
#    properties:
#      hibernate:
#        ddl-auto: update
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        temp:
#          use_jdbc_metadata_defaults: false

  security:
    user:
      name: admin
      password: admin
---
server:
  port: 8090
---
spring:
  profiles: test
  h2:
    console:
      enabled: true

spring.jpa:
  hibernate.ddl-auto: create-drop

hotel.service:
  name: 'test profile:'

logging:
  file: boot_example.log
  org.hibernate: INFO

specific:
  jenkins_user: izeghouh
  jenkins_token: 59bec667a95aa18b1f8d5fecd49d987e
  jenkins_base_url: https://ci.int0.aub.cloudwatt.net

