# Spring Boot configuration
---
spring:
  jmx:
    enabled: false
---
server:
  port: 8090
#todo: make sure to always enable security in production
security:
  basic:
    enabled: false
#management endpoints on a separate port
management:
  port: 8095
  security:
    enabled: false # management port is internal only. no need to secure it.
#default project info followed by actual injected pom-specified values.
project:
  name: spring-boot-rest-example
  version: 0.1
  description: boot-example default description
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

hotel.service:
  name: 'default profile:'

---
spring:
  profiles: test
  h2:
    console:
      enabled: true

spring.jpa:
  hibernate.ddl-auto: create-drop

hotel.service:
  name: 'test profile:'

logging:
  file: boot_example.log
  org.hibernate: INFO

specific:
  jenkins_user: izeghouh
  jenkins_token: 59bec667a95aa18b1f8d5fecd49d987e
  jenkins_base_url: https://ci.int0.aub.cloudwatt.net

