# Spring Boot configuration
---
spring:
#  # Database
#  datasource:
#    url: "jdbc:postgresql://localhost:5432/jenkins"
#    username:
#    password:
#  # JPA properties
#  jpa:
#    properties:
#      hibernate:
#        ddl-auto: update
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        temp:
#          use_jdbc_metadata_defaults: false

  security:
    user:
      name: admin
      password: admin
---
server:
  port: 8090
---
spring:
  profiles: test
  h2:
    console:
      enabled: true
spring.banner.location: classpath:/banner.txt
spring.jpa:
  hibernate.ddl-auto: create-drop

hotel.service:
  name: 'test profile:'

logging:
  file: boot_example.log
  org.hibernate: INFO
  root: INFO

specific:
  jenkins_user: #username
  jenkins_token: #token
  jenkins_base_url: #url